### PR TITLE
svg template for collapse/expand

### PR DESCRIPTION
**Pull request by ihm4u**
Hi @tobibeer 

Can you test the svg-collapse branch and see if it works for you?

Maybe you can do a nicer template :)

I'd rather have two separate templates, since I want to have the least number of elements in the DOM as possible

### CODE REVIEW

**Comment by ihm4u** [comment]
BTW, feel free to change around and make it look really nice!

**Comment by tobibeer** [comment]
will do, thx

**Comment by tobibeer** [comment]
Hi, @ihm4u, looks just perfect to the eye of this beholder, and easily customizable. :+1: 

Not exactly sure where to best document these details. I'd only ship the very essentials with the plugin.

I'd propose some modifications to the docs but right now I'm trying to figure out how to best go about that myself. I'm expecting to have a myriad of plugins in a bit and — while it is good to have each plugin in a separate repo — it might not be the best idea to have one TiddlyWiki for each plugin documentation, as the GitHub pages site will eventually grow a lot with all these TiddlyWikis.

What I will perhaps build, though, in the **gh-pages** branch of a plugin repo, are static pages:
1. to test if it works / what doesn't
2. to learn more about that
3. to provide slim output

...and then one big **tobibeer/tw5-plugins** wiki that will contain the detailed documentation for all plugins.

**Comment by ihm4u** [comment]
Alright, sounds great. I still don't know how to deal with the docs either....we'll have to wait and try different things and see how it goes.

**Pull request merged**
